### ISSUE TITLE
The program's automatically determined is invalid

### ISSUE THREAD

**Issue by zxgsy520** [katholt/Kaptive#18]
···
Error: multiple possible locus labels were found: K locus, K type
Please use the --locus_label option to specify which to use
···
The program's automatically determined is invalid

**Comment by zxgsy520** [comment]
![image](https://user-images.githubusercontent.com/36355222/149732584-3f03d9c6-3606-4bd1-b3a7-4d86581527ed.png)
Version v0.5.1 has bugs
···
def find_locus_label(genbank):
    """
    Automatically finds the label for the locus sequences. The Genbank file must have exactly one
    possible label that is present in a note qualifier in the source feature for every record. If
    not, Kaptive will quit with an error.
    """
    possible_locus_labels = set()
    for record in SeqIO.parse(genbank, 'genbank'):
        for feature in record.features:
            if feature.type == 'source' and 'note' in feature.qualifiers:
                for note in feature.qualifiers['note']: 
                    if "locus" not in note:    #add
                        continue
                    if ':' in note:
                        possible_locus_labels.add(note.split(':')[0].strip())
                    if '=' in note:
                        possible_locus_labels.add(note.split('=')[0].strip())

···

**Comment by rrwick** [comment]
Hi,

I think this error results from a mismatch between versions of the program (`kaptive.py`) and the reference database (e.g. `Klebsiella_k_locus_primary_reference.gbk`).

For example, if I use the current program (v2.0.0) with the current database (v2.0.0), I cannot replicate this error. However, if I use an old version of the program (v0.7.3) with the current database (v2.0.0), then I can. The code snippet you included also seems to be from an old version of the program.

So I pretty sure that if you grab the current version of the program (which is in bioconda), this should no longer be a problem :smile:

Ryan
