### ISSUE TITLE
plasmids in Klebsiella

### ISSUE THREAD

**Issue by abrozzi** [katholt/Kaptive#19]
Dears,

I was wondering what's your favorite tool to detect plasmids in genome sequencing (contigs) of Klebsiella?

Thank you,
-A

**Comment by katholt** [comment]
This is not really the forum to ask general Klebsiella analysis Qs! However our group has published a paper on classifying contigs as plasmid vs chromosome using kraken with a custom DB, which we found to be better than the dedicated tools available such as mlplasmids. See https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000550

**Comment by abrozzi** [comment]
Apologies. I  expected in GitHub the possibility to change labels (issue, question, comment).
I thank you very much for your fruitfull answer.

Again, my apologies.
-A
