### ISSUE TITLE
Please checkout patches applied to the Debian packaged version

### ISSUE THREAD

**Issue by tillea** [katholt/Kaptive#20]
Hi,
I've just updated the Debian package of Kaptive.  We had to apply [three patches](https://salsa.debian.org/med-team/kaptive/-/tree/master/debian/patches) which I'd recommend to apply in your source code.  Two of the patches are connected to ncbi-blast+ the third patch helps when using latest version of the `which` command.  All patches are containing a description in their header so you can easily decide what you want to take over.
Kind regards, Andreas.

**Comment by rrwick** [comment]
Thanks! The patches look fine, so I've committed the changes: 42c82a6. So unless something comes up, these should appear in the next version of Kaptive :smile:

Ryan

**Comment by tillea** [comment]
Am Sun, Jan 23, 2022 at 09:13:44PM -0800 schrieb Ryan Wick:
> Thanks! The patches look fine, so I've committed the changes: 42c82a6. So unless something comes up, these should appear in the next version of Kaptive :smile:
Thanks a lot, Andreas.
