### ISSUE TITLE
kaptive.py --version prints v2.0.0

### ISSUE THREAD

**Issue by stitam** [katholt/Kaptive#23]
Just a note, while the latest release is v2.0.2, it seems the kaptive.py script still contains `__version__ = '2.0.0'` and I see the same in the released v2.0.2 source code as well.

**Comment by rrwick** [comment]
Thank you for pointing this out! I've made that mistake before 🤦 I've just bumped the version in code to 2.0.3 and made a new release: https://github.com/katholt/Kaptive/releases/tag/v2.0.3
