### ISSUE TITLE
New feature suggestion for improving prediction speed

### ISSUE THREAD

**Issue by stitam** [katholt/Kaptive#24]
Hi, I noticed in my pipeline that kaptive requires a considerable amount of time to complete, analytics points towards memory usage as a potential culprit. I was wondering whether this is because of blast, and if yes, whether this could be improved by using e.g. diamond (https://github.com/bbuchfink/diamond) instead of blast in a subsequent release? I assume any speed-up would impact web API as well, which also seems to be quite slow at times. Many thanks.

**Comment by tomdstanton** [comment]
Significant speed-up implemented in Kaptive v3.
