### ISSUE TITLE
About the k or o-locus database

### ISSUE THREAD

**Issue by huizhen2014** [katholt/Kaptive#5]
Hi, I am new to kaptive. I have noticed we could get the reference database about the  Klebsiella from here.
Since my bacteria is  Acinetobacter_baumannii, could you tell me where can I get my bacterial K and o locus database? 
Thank you!

**Comment by kelwyres** [comment]
Hi Carlos, 
Thanks for your interest in using Kaptive. Unfortunately we don't yet have a database for A. baumannii capsule loci but our collaborators, Joanna Kenyon and Ruth Hall, are in the process of putting one together. This will be added to the Kaptive repository as soon as it is ready (hopefully in the next few weeks). I can send another note to let you know when this happens.
Thanks.

**Comment by huizhen2014** [comment]
I get it, very look forward to it.
Thanks!

**Comment by kelwyres** [comment]
Hi Carlos, 

Just checking over these older issues. In case you haven't seen it yet, we do now have K and OL locus databases for A. baumannii included with Kaptive and Kaptive Web. You can access them here: https://github.com/katholt/Kaptive/tree/master/reference_database

Thanks,
Kelly

**Comment by huizhen2014** [comment]
Hi Kelly,


I am glad to hear that, it will be helpful to my.


Thanks,
Carlos


 Original Message 
Sender: kelwyres<notifications@github.com>
Recipient: katholt/Kaptive<Kaptive@noreply.github.com>
Cc: Carlos Hui<huizhen_2014@163.com>; Author<author@noreply.github.com>
Date: Wednesday, Feb 10, 2021 12:39
Subject: Re: [katholt/Kaptive] About the k or o-locus database (#5)


Hi Carlos,
Just checking over these older issues. In case you haven't seen it yet, we do now have K and OL locus databases for A. baumannii included with Kaptive and Kaptive Web. You can access them here: https://github.com/katholt/Kaptive/tree/master/reference_database
Thanks,
 Kelly
