### ISSUE TITLE
Error: tblastn crashed

### ISSUE THREAD

**Issue by mingjuhao** [katholt/Kaptive#7]
When i was using the Klebsiella_k_locus_primary_reference.gbk as reference, this error happened. But for other reference db such as o_locus, It runs normally. I can't figure it out.

**Comment by mingjuhao** [comment]
I resolved the problem when i tried again. I guess it might be the internet.

**Comment by emmadoughty** [comment]
I'm having issues too with "Error: tblastn crashed!" being reported after Kaptive has run through a couple of A. baumannii assemblies. I've tried installing Kaptive in various ways (from git cloning, from pip) and installing blast in multiple ways/environments but with no joy. Any information about the blast version that you are using or any other recommendations you have to get this going would be greatly appreciated. Many thanks, Emma

**Comment by kelwyres** [comment]
Hi Emma, 
It this a persistent or a sporadic crash? Unfortunately, there is a problem with some versions of blast+ that causes a sporadic crash with tblastn when using multithreading. As far as we can tell, v2.3.0 and earlier are not impacted, but several of the later versions are. So in the first instance I recommend trying v2.3.0 or running Kaptive with the "--threads 1" option. If this still doesn't fix the problem, or if you are seeing a persistent crash, could you please send an example of the command you are using and an example input assembly- you can send via email if you prefer (kelly.wyres@monash.edu).
Thanks.
Kelly
